import { Container, Typography } from '@mui/joy'
import Head from 'next/head'
// import useCards from '../src/model/useCards'
// import CardComp from '../src/component/cardComp'
import styles from '../styles/Home.module.css'

export default function Home() {
  // const { cards, fetchCards } = useCards()

  return (
    <div className={styles.container}>
      <Head>
        <title>Clash Royale API Demo</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Container>
        <Typography>
          This Website just meant to be practice for React.js / Next.js / JoyUI
        </Typography>
        {/* <Button onClick={fetchCards}>get cards</Button>
        {cards && (
          <div
            style={{
              display: 'flex',
              flexWrap: 'wrap',
            }}
          >
            {cards.map((card) => (
              <CardComp key={card.id} card={card} />
            ))}
          </div>
        )} */}
      </Container>
    </div>
  )
}
