import { Button, Card, CardContent, CardCover, Typography } from "@mui/joy";
import Head from "next/head";
import Image from "next/image";
import useCards from "../src/model/useCards";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { cards, fetchCards } = useCards();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Button onClick={fetchCards}>get cards</Button>
      {cards && (
        <div
          style={{
            display: "flex",
            maxWidth: 800,
            margin: "auto",
            flexWrap: "wrap",
          }}
        >
          {cards.map((card) => (
            <Card
              key={card.id}
              style={{
                margin: 8,
                padding: 4,
                width: 108,
                height: 185,
                border: "1px solid grey",
                borderRadius: 8,
                textAlign: "center",
              }}
            >
              <CardCover>
                <Image
                  width={100}
                  height={130}
                  // style={{ objectFit: "cover" }}
                  objectFit={"cover"}
                  layout={"fixed"}
                  src={card.iconUrls.medium}
                  priority={true}
                  alt={card.name + "\n not available"}
                />
              </CardCover>
              <br />
              <CardContent
                sx={{
                  bottom: 4,
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "flex-end",
                }}
              >
                <Typography textAlign={"center"}>{card.name}</Typography>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {/* <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  );
}
